# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 1

[[main]]
  name = "Survey"
  url = "#survey"
  weight = 3



#[[main]]
#  name = "Open Case Study Search"
#  url = "#findbpcs"
#  weight = 25



#[[main]]
#  name = "Data Science search"
#  url = "#projects"
#  weight = 35

#[[main]]
#  name = "Stats search"
#  url = "#statsprojects"
#  weight = 36

#[[main]]
#  name = "OCS search"
#  url = "#contextprojects"
#  weight = 37

#[[main]]
# name = "Open Case Studies"
# url = "#ocs"
# weight = 50

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 40


[[main]]
  name = "Team"
  url = "#team"
  weight = 50


[[main]]
  name = "Talks"
  url = "#talks"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

[[main]]
  name = "Open Case Study Search"
  url = "#searchtab"
  weight = 90


#[[main]]
#  name = "Open Case Study Search"
#  url = "#search"
#  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
